local mod = get_mod("markers_aio")

local apply_color_to_text = function(text, r, g, b)
	return "{#color(" .. r .. "," .. g .. "," .. b .. ")}" .. text .. "{#reset()}"
end

local fonts = mod._get_font_options()

local Gold = mod.lookup_border_color("Gold")
local Silver = mod.lookup_border_color("Silver")
local Steel = mod.lookup_border_color("Steel")
local Tarnished = mod.lookup_border_color("Tarnished")

local border_colours = {
	{
		text = apply_color_to_text(mod:localize("Gold"), Gold[2], Gold[3], Gold[4]),
		value = "Gold",
	},
	{
		text = apply_color_to_text(mod:localize("Silver"), Silver[2], Silver[3], Silver[4]),
		value = "Silver",
	},
	{
		text = apply_color_to_text(mod:localize("Steel"), Steel[2], Steel[3], Steel[4]),
		value = "Steel",
	},
	{
		text = apply_color_to_text(mod:localize("Tarnished"), Tarnished[2], Tarnished[3], Tarnished[4]),
		value = "Tarnished",
	},
}

local chest_icons = {
	{
		text = "Default",
		value = "content/ui/materials/hud/interactions/icons/default",
		icon = "content/ui/materials/hud/interactions/icons/default",
	},
	{
		text = "Video",
		value = "content/ui/materials/icons/system/settings/category_video",
		icon = "content/ui/materials/icons/system/settings/category_video",
	},
	{
		text = "Loot",
		value = "content/ui/materials/icons/generic/loot",
		icon = "content/ui/materials/icons/generic/loot",
	},
}

local luggable_icons = {
	{
		text = "Exclamation",
		value = "content/ui/materials/hud/interactions/icons/environment_alert",
		icon = "content/ui/materials/hud/interactions/icons/environment_alert",
	},
	{
		text = "Hands",
		value = "content/ui/materials/hud/communication_wheel/icons/thanks",
		icon = "content/ui/materials/hud/communication_wheel/icons/thanks",
	},
	{
		text = "Fist",
		value = "content/ui/materials/icons/presets/preset_18",
		icon = "content/ui/materials/icons/presets/preset_18",
	},
	{
		text = "Luggable",
		value = "content/ui/materials/icons/player_states/lugged",
		icon = "content/ui/materials/icons/player_states/lugged",
	},
}

local background_colours = {
	{
		text = "Black",
		value = "Black",
	},
	{
		text = "Terminal",
		value = "Terminal",
	},
}
local distance_text_positions = {
	{
		text = "Top",
		value = "Top",
	},
	{
		text = "Bottom",
		value = "Bottom",
	},
	{
		text = "Left",
		value = "Left",
	},
	{
		text = "Right",
		value = "Right",
	},
	{
		text = "Center",
		value = "Center",
	},
}
return {
	name = mod:localize("mod_name"),
	description = mod:localize("mod_description"),
	is_togglable = false,
	options = {
		widgets = {

			-- GLOBAL
			{
				setting_id = "aio_settings",
				type = "group",
				tab = "General",
				sub_widgets = {
					{
						setting_id = "mod_name_pizazz_toggle",
						type = "checkbox",
						default_value = true,
						tab = "General",
						tooltip = "mod_name_pizazz_tooltip",
					},
					{
						setting_id = "los_fade_enable",
						type = "checkbox",
						default_value = true,
						tab = "General",
						tooltip = "los_fade_enable_tooltip",
					},
					{
						setting_id = "los_opacity",
						type = "numeric",
						tab = "General",
						default_value = 50,
						range = { 0, 100 },
						step_size = 1,
						tooltip = "los_opacity_tooltip",
					},
					{
						setting_id = "ads_los_opacity",
						type = "numeric",
						tab = "General",
						default_value = 50,
						range = { 0, 100 },
						step_size = 1,
						tooltip = "ads_los_opacity_tooltip",
					},
					{
						setting_id = "marker_background_colour",
						type = "dropdown",
						options = background_colours,
						default_value = "Terminal",
						tab = "General",
						tooltip = "marker_background_colour_tooltip",
					},
					{
						setting_id = "font_type",
						type = "dropdown",
						options = fonts,
						default_value = "mono_tide_bold",
						tab = "General",
						tooltip = "font_type_tooltip",
					},
					{
						setting_id = "distance_text_enable",
						type = "checkbox",
						default_value = true,
						tab = "General",
						tooltip = "distance_text_enable_tooltip",
					},
					{
						setting_id = "distance_text_position",
						type = "dropdown",
						options = distance_text_positions,
						default_value = "Bottom",
						tab = "General",
						tooltip = "distance_text_position_tooltip",
					},
					{
						setting_id = "distance_text_scale",
						type = "numeric",
						tab = "General",
						default_value = 100,
						range = { 50, 150 },
						step_size = 1,
						tooltip = "scale_tooltip",
					},
				},
			},

			-- AMMO / MED
			{

				setting_id = "ammo_med_markers_settings",
				type = "group",
				tab = "Ammo & Med",
				sub_widgets = {
					{
						setting_id = "ammo_med_enable",
						type = "checkbox",
						default_value = true,
						tab = "Ammo & Med",
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "ammo_med_markers_alternate_large_ammo_icon",
						type = "checkbox",
						default_value = true,
						tab = "Ammo & Med",
						tooltip = "ammo_med_markers_alternate_large_ammo_icon_tooltip",
					},
					{
						setting_id = "ammo_med_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tab = "Ammo & Med",
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "ammo_med_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tab = "Ammo & Med",
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "ammo_med_toggle_los",
						type = "keybind",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "ammo_med_toggle_los",
						tab = "Ammo & Med",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "ammo_med_max_distance",
						type = "numeric",
						tab = "Ammo & Med",
						default_value = 50,
						range = { 0, 100 },
						step_size = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "med_station_max_distance",
						type = "numeric",
						tab = "Ammo & Med",
						default_value = 20,
						range = { 0, 100 },
						step_size = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "ammo_med_scale",
						type = "numeric",
						tab = "Ammo & Med",
						default_value = 100,
						range = { 50, 150 },
						step_size = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "ammo_med_alpha",
						type = "numeric",
						tab = "Ammo & Med",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "display_ammo_charges",
						type = "checkbox",
						default_value = true,
						tab = "Ammo & Med",
						tooltip = "display_ammo_charges_tooltip",
					},
					{
						setting_id = "display_med_charges",
						type = "checkbox",
						default_value = true,
						tab = "Ammo & Med",
						tooltip = "display_med_charges_tooltip",
					},
					{
						setting_id = "change_colour_for_ammo_charges",
						type = "checkbox",
						default_value = true,
						tab = "Ammo & Med",
						tooltip = "change_colour_for_ammo_charges_tooltip",
					},
					{
						setting_id = "display_field_improv_icon",
						type = "checkbox",
						default_value = true,
						tab = "Ammo & Med",
						tooltip = "display_field_improv_icon_tooltip",
					},
					{
						setting_id = "display_med_ring",
						type = "checkbox",
						default_value = true,
						tab = "Ammo & Med",
						tooltip = "display_med_ring_tooltip",
					},
					{
						setting_id = "display_field_improv_colour",
						type = "checkbox",
						default_value = true,
						tab = "Ammo & Med",
						tooltip = "display_field_improv_colour_tooltip",
					},

					{
						setting_id = "field_improv_colour",
						type = "group",
						tab = "Ammo & Med",
						sub_widgets = {
							{ setting_id = "field_improv_colour_R", type = "numeric", default_value = 50, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "field_improv_colour_G", type = "numeric", default_value = 0, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "field_improv_colour_B", type = "numeric", default_value = 255, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},

					{
						setting_id = "ammo_small_colour",
						type = "group",
						tab = "Ammo & Med",
						sub_widgets = {
							{ setting_id = "ammo_small_colour_R", type = "numeric", default_value = 252, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "ammo_small_colour_G", type = "numeric", default_value = 252, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "ammo_small_colour_B", type = "numeric", default_value = 222, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},

					{
						setting_id = "ammo_small_border_colour",
						type = "dropdown",
						tab = "Ammo & Med",
						options = border_colours,
						default_value = "Silver",
						tooltip = "border_colour_tooltip",
					},

					{
						setting_id = "ammo_large_colour",
						type = "group",
						tab = "Ammo & Med",
						sub_widgets = {
							{ setting_id = "ammo_large_colour_R", type = "numeric", default_value = 252, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "ammo_large_colour_G", type = "numeric", default_value = 252, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "ammo_large_colour_B", type = "numeric", default_value = 222, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},

					{
						setting_id = "ammo_large_border_colour",
						type = "dropdown",
						tab = "Ammo & Med",
						options = border_colours,
						default_value = "Silver",
						tooltip = "border_colour_tooltip",
					},

					{
						setting_id = "ammo_crate_colour",
						type = "group",
						tab = "Ammo & Med",
						sub_widgets = {
							{ setting_id = "ammo_crate_colour_R", type = "numeric", default_value = 252, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "ammo_crate_colour_G", type = "numeric", default_value = 252, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "ammo_crate_colour_B", type = "numeric", default_value = 222, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},

					{
						setting_id = "ammo_crate_border_colour",
						type = "dropdown",
						tab = "Ammo & Med",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},

					{
						setting_id = "med_crate_colour",
						type = "group",
						tab = "Ammo & Med",
						sub_widgets = {
							{ setting_id = "med_crate_colour_R", type = "numeric", default_value = 252, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "med_crate_colour_G", type = "numeric", default_value = 252, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "med_crate_colour_B", type = "numeric", default_value = 222, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},

					{
						setting_id = "med_crate_border_colour",
						type = "dropdown",
						tab = "Ammo & Med",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},

					{
						setting_id = "grenade_colour",
						type = "group",
						tab = "Ammo & Med",
						sub_widgets = {
							{ setting_id = "grenade_colour_R", type = "numeric", default_value = 252, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "grenade_colour_G", type = "numeric", default_value = 252, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "grenade_colour_B", type = "numeric", default_value = 222, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},

					{
						setting_id = "grenade_border_colour",
						type = "dropdown",
						tab = "Ammo & Med",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
				},
			},

			-- CHESTS
			{

				setting_id = "chest_markers_settings",
				type = "group",
				tab = "Chests",
				sub_widgets = {
					{
						setting_id = "chest_enable",
						type = "checkbox",
						default_value = true,
						tab = "Chests",
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "chest_icon",
						type = "dropdown",
						options = chest_icons,
						default_value = "content/ui/materials/icons/system/settings/category_video",
						tab = "Chests",
						tooltip = "icon_tooltip",
					},
					{
						setting_id = "chest_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tab = "Chests",
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "chest_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tab = "Chests",
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "chest_toggle_los",
						type = "keybind",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "chest_toggle_los",
						tab = "Chests",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "chest_max_distance",
						type = "numeric",
						tab = "Chests",
						default_value = 50,
						range = { 0, 100 },
						step_size = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "chest_scale",
						type = "numeric",
						tab = "Chests",
						default_value = 100,
						range = { 50, 150 },
						step_size = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "chest_alpha",
						type = "numeric",
						tab = "Chests",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "chest_icon_colour",
						type = "group",
						tab = "Chests",
						sub_widgets = {
							{ setting_id = "chest_icon_colour_R", type = "numeric", default_value = 252, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "chest_icon_colour_G", type = "numeric", default_value = 252, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "chest_icon_colour_B", type = "numeric", default_value = 222, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
					{
						setting_id = "chest_border_colour",
						type = "dropdown",
						tab = "Chests",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
				},
			},

			-- HERETICAL IDOL
			{

				setting_id = "heretical_idol_markers_settings",
				type = "group",
				tab = "Heretical Idol",
				sub_widgets = {
					{
						setting_id = "heretical_idol_enable",
						type = "checkbox",
						default_value = true,
						tab = "Heretical Idol",
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "heretical_idol_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tab = "Heretical Idol",
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "heretical_idol_require_line_of_sight",
						type = "checkbox",
						default_value = false,
						tab = "Heretical Idol",
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "heretical_idol_toggle_los",
						type = "keybind",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "heretical_idol_toggle_los",
						tab = "Heretical Idol",
						tooltip = "toggle_los_tooltip",
					},

					{
						setting_id = "heretical_idol_max_distance",
						type = "numeric",
						tab = "Heretical Idol",
						default_value = 50,
						range = { 0, 100 },
						step_size = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "heretical_idol_scale",
						type = "numeric",
						tab = "Heretical Idol",
						default_value = 100,
						range = { 50, 150 },
						step_size = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "heretical_idol_alpha",
						type = "numeric",
						tab = "Heretical Idol",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "icon_colour",
						type = "group",
						tab = "Heretical Idol",
						sub_widgets = {
							{ setting_id = "icon_colour_R", type = "numeric", default_value = 132, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "icon_colour_G", type = "numeric", default_value = 156, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "icon_colour_B", type = "numeric", default_value = 99, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},

					{
						setting_id = "idol_border_colour",
						type = "dropdown",
						tab = "Heretical Idol",
						options = border_colours,
						default_value = "Tarnished",
						tooltip = "border_colour_tooltip",
					},
				},
			},

			-- MATERIALS
			{

				setting_id = "material_markers_settings",
				type = "group",
				tab = "Materials",
				sub_widgets = {
					{
						setting_id = "material_enable",
						type = "checkbox",
						default_value = true,
						tab = "Materials",
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "material_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tab = "Materials",
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "material_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tab = "Materials",
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "material_toggle_los",
						type = "keybind",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "material_toggle_los",
						tab = "Materials",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "material_max_distance",
						type = "numeric",
						tab = "Materials",
						default_value = 50,
						range = { 0, 100 },
						step_size = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "material_scale",
						type = "numeric",
						tab = "Materials",
						default_value = 100,
						range = { 50, 150 },
						step_size = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "material_alpha",
						type = "numeric",
						tab = "Materials",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "marker_toggles",
						type = "group",
						tab = "Materials",
						sub_widgets = {
							{
								setting_id = "toggle_large_plasteel",
								type = "checkbox",
								tab = "Materials",
								default_value = true,
							},
							{
								setting_id = "toggle_small_plasteel",
								type = "checkbox",
								tab = "Materials",
								default_value = true,
							},
							{
								setting_id = "toggle_large_diamantine",
								type = "checkbox",
								tab = "Materials",
								default_value = true,
							},
							{
								setting_id = "toggle_small_diamantine",
								type = "checkbox",
								tab = "Materials",
								default_value = true,
							},
						},
					},
					{
						setting_id = "material_small_border_colour",
						type = "dropdown",
						tab = "Materials",
						options = border_colours,
						default_value = "Silver",
						tooltip = "border_colour_tooltip",
					},
					{
						setting_id = "material_large_border_colour",
						type = "dropdown",
						tab = "Materials",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
					{
						setting_id = "plasteel_icon_colour",
						type = "group",
						tab = "Materials",
						sub_widgets = {
							{ setting_id = "plasteel_icon_colour_R", type = "numeric", default_value = 243, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "plasteel_icon_colour_G", type = "numeric", default_value = 115, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "plasteel_icon_colour_B", type = "numeric", default_value = 85, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
					{
						setting_id = "diamantine_icon_colour",
						type = "group",
						tab = "Materials",
						sub_widgets = {
							{ setting_id = "diamantine_icon_colour_R", type = "numeric", default_value = 95, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "diamantine_icon_colour_G", type = "numeric", default_value = 158, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "diamantine_icon_colour_B", type = "numeric", default_value = 160, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
				},
			},

			-- STIMM
			{

				setting_id = "stimm_markers_settings",
				type = "group",
				tab = "Stimms",
				sub_widgets = {
					{
						setting_id = "stimm_enable",
						type = "checkbox",
						default_value = true,
						tab = "Stimms",
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "recolor_stimm_compat_enable",
						type = "checkbox",
						default_value = true,
						tab = "Stimms",
						tooltip = "recolor_stimm_compat_enable_tooltip",
					},
					{
						setting_id = "toggle_background_colour",
						type = "checkbox",
						default_value = false,
						tab = "Stimms",
						tooltip = "toggle_background_colour_tooltip",
					},
					{
						setting_id = "broker_stimm_enable",
						type = "checkbox",
						default_value = true,
						tab = "Stimms",
						tooltip = "stimm_enable_tooltip",
					},
					{
						setting_id = "stimm_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tab = "Stimms",
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "stimm_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tab = "Stimms",
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "stimm_toggle_los",
						type = "keybind",
						function_name = "stimm_toggle_los",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						tab = "Stimms",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "stimm_max_distance",
						type = "numeric",
						tab = "Stimms",
						default_value = 50,
						range = { 0, 100 },
						step_size = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "stimm_scale",
						type = "numeric",
						tab = "Stimms",
						default_value = 100,
						range = { 50, 150 },
						step_size = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "stimm_alpha",
						type = "numeric",
						tab = "Stimms",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "boost_stimm_icon_colour",
						type = "group",
						tab = "Stimms",
						sub_widgets = {
							{ setting_id = "boost_stimm_icon_colour_R", type = "numeric", default_value = 255, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "boost_stimm_icon_colour_G", type = "numeric", default_value = 255, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "boost_stimm_icon_colour_B", type = "numeric", default_value = 30, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
					{
						setting_id = "boost_stimm_border_colour",
						type = "dropdown",
						tab = "Stimms",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},

					{
						setting_id = "corruption_stimm_icon_colour",
						type = "group",
						tab = "Stimms",
						sub_widgets = {
							{ setting_id = "corruption_stimm_icon_colour_R", type = "numeric", default_value = 30, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "corruption_stimm_icon_colour_G", type = "numeric", default_value = 255, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "corruption_stimm_icon_colour_B", type = "numeric", default_value = 30, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
					{
						setting_id = "corruption_stimm_border_colour",
						type = "dropdown",
						tab = "Stimms",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},

					{
						setting_id = "power_stimm_icon_colour",
						type = "group",
						tab = "Stimms",
						sub_widgets = {
							{ setting_id = "power_stimm_icon_colour_R", type = "numeric", default_value = 255, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "power_stimm_icon_colour_G", type = "numeric", default_value = 30, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "power_stimm_icon_colour_B", type = "numeric", default_value = 30, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
					{
						setting_id = "power_stimm_border_colour",
						type = "dropdown",
						tab = "Stimms",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},

					{
						setting_id = "speed_stimm_icon_colour",
						type = "group",
						tab = "Stimms",
						sub_widgets = {
							{ setting_id = "speed_stimm_icon_colour_R", type = "numeric", default_value = 30, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "speed_stimm_icon_colour_G", type = "numeric", default_value = 150, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "speed_stimm_icon_colour_B", type = "numeric", default_value = 255, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
					{
						setting_id = "speed_stimm_border_colour",
						type = "dropdown",
						tab = "Stimms",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},

					{
						setting_id = "broker_stimm_icon_colour",
						type = "group",
						tab = "Stimms",
						sub_widgets = {
							{ setting_id = "broker_stimm_icon_colour_R", type = "numeric", default_value = 200, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "broker_stimm_icon_colour_G", type = "numeric", default_value = 20, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "broker_stimm_icon_colour_B", type = "numeric", default_value = 200, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
					{
						setting_id = "broker_stimm_border_colour",
						type = "dropdown",
						tab = "Stimms",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
				},
			},

			-- TOMES
			{

				setting_id = "tome_markers_settings",
				type = "group",
				tab = "Tomes",
				sub_widgets = {
					{
						setting_id = "tome_enable",
						type = "checkbox",
						default_value = true,
						tab = "Tomes",
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "tome_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tab = "Tomes",
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "tome_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tab = "Tomes",
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "tome_toggle_los",
						type = "keybind",
						function_name = "tome_toggle_los",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						tab = "Tomes",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "tome_max_distance",
						type = "numeric",
						tab = "Tomes",
						default_value = 50,
						range = { 0, 100 },
						step_size = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "tome_scale",
						type = "numeric",
						tab = "Tomes",
						default_value = 100,
						range = { 50, 150 },
						step_size = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "tome_alpha",
						type = "numeric",
						tab = "Tomes",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "grim_colour",
						type = "group",
						tab = "Tomes",
						sub_widgets = {
							{ setting_id = "grim_colour_R", type = "numeric", default_value = 150, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "grim_colour_G", type = "numeric", default_value = 252, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "grim_colour_B", type = "numeric", default_value = 0, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
					{
						setting_id = "script_colour",
						type = "group",
						tab = "Tomes",
						sub_widgets = {
							{ setting_id = "script_colour_R", type = "numeric", default_value = 255, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "script_colour_G", type = "numeric", default_value = 252, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "script_colour_B", type = "numeric", default_value = 0, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
					{
						setting_id = "tome_border_colour",
						type = "dropdown",
						tab = "Tomes",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
				},
			},

			-- LUGGABLE
			{

				setting_id = "luggable_markers_settings",
				type = "group",
				tab = "Luggables",
				sub_widgets = {
					{
						setting_id = "luggable_enable",
						type = "checkbox",
						default_value = true,
						tab = "Luggables",
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "luggable_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tab = "Luggables",
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "luggable_require_line_of_sight",
						type = "checkbox",
						default_value = false,
						tab = "Luggables",
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "luggable_toggle_los",
						type = "keybind",
						function_name = "luggable_toggle_los",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						tab = "Luggables",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "luggable_icon",
						type = "dropdown",
						options = luggable_icons,
						default_value = "content/ui/materials/hud/interactions/icons/environment_alert",
						tab = "Luggables",
						tooltip = "icon_tooltip",
					},
					{
						setting_id = "luggable_max_distance",
						type = "numeric",
						tab = "Luggables",
						default_value = 50,
						range = { 0, 100 },
						step_size = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "luggable_scale",
						type = "numeric",
						tab = "Luggables",
						default_value = 100,
						range = { 50, 150 },
						step_size = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "luggable_alpha",
						type = "numeric",
						tab = "Luggables",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "luggable_colour",
						type = "group",
						tab = "Luggables",
						sub_widgets = {
							{ setting_id = "luggable_colour_R", type = "numeric", default_value = 0, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "luggable_colour_G", type = "numeric", default_value = 240, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "luggable_colour_B", type = "numeric", default_value = 255, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
					{
						setting_id = "luggable_border_colour",
						type = "dropdown",
						tab = "Luggables",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
				},
			},

			-- MARTYR SKULL
			{

				setting_id = "martyrs_skull_markers_settings",
				type = "group",
				tab = "Martyr's Skull",
				sub_widgets = {
					{
						setting_id = "martyrs_skull_enable",
						type = "checkbox",
						default_value = true,
						tab = "Martyr's Skull",
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "martyrs_skull_guide_enable",
						type = "checkbox",
						default_value = true,
						tab = "Martyr's Skull",
						tooltip = "martyrs_skull_guide_enable_tooltip",
					},
					{
						setting_id = "martyrs_skull_guide_disable_if_collected",
						type = "checkbox",
						default_value = true,
						tab = "Martyr's Skull",
						tooltip = "martyrs_skull_guide_disable_if_collected_tooltip",
					},
					{
						setting_id = "martyrs_skull_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tab = "Martyr's Skull",
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "martyrs_skull_require_line_of_sight",
						type = "checkbox",
						default_value = false,
						tab = "Martyr's Skull",
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "martyrs_skull_toggle_los",
						type = "keybind",
						function_name = "martyrs_skull_toggle_los",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						tab = "Martyr's Skull",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "martyrs_skull_max_distance",
						type = "numeric",
						tab = "Martyr's Skull",
						default_value = 50,
						range = { 0, 100 },
						step_size = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "martyrs_skull_scale",
						type = "numeric",
						tab = "Martyr's Skull",
						default_value = 100,
						range = { 50, 150 },
						step_size = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "martyrs_skull_alpha",
						type = "numeric",
						tab = "Martyr's Skull",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "martyrs_skull_colour",
						type = "group",
						tab = "Martyr's Skull",
						sub_widgets = {
							{ setting_id = "martyrs_skull_colour_R", type = "numeric", default_value = 255, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "martyrs_skull_colour_G", type = "numeric", default_value = 200, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "martyrs_skull_colour_B", type = "numeric", default_value = 0, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
					{
						setting_id = "martyrs_skull_border_colour",
						type = "dropdown",
						tab = "Martyr's Skull",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
				},
			},

			-- EXPEDITION
			{

				setting_id = "expedition_markers_settings",
				type = "group",
				tab = "Expedition",
				sub_widgets = {
					{
						setting_id = "expedition_enable",
						type = "checkbox",
						default_value = true,
						tab = "Expedition",
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "expedition_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tab = "Expedition",
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "expedition_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tab = "Expedition",
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "expedition_toggle_los",
						type = "keybind",
						function_name = "expedition_toggle_los",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						tab = "Expedition",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "expedition_max_distance",
						type = "numeric",
						tab = "Expedition",
						default_value = 50,
						range = { 0, 100 },
						step_size = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "expedition_scale",
						type = "numeric",
						tab = "Expedition",
						default_value = 100,
						range = { 50, 150 },
						step_size = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "expedition_alpha",
						type = "numeric",
						tab = "Expedition",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size = 0.05,
						tooltip = "alpha_tooltip",
					},

					{
						setting_id = "expedition_border_colour",
						type = "dropdown",
						tab = "Expedition",
						options = border_colours,
						default_value = "Silver",
						tooltip = "border_colour_tooltip",
					},
					{
						setting_id = "expedition_border_colour_1",
						type = "dropdown",
						tab = "Expedition",
						options = border_colours,
						default_value = "Tarnished",
						tooltip = "border_colour_tooltip",
					},
					{
						setting_id = "expedition_border_colour_2",
						type = "dropdown",
						tab = "Expedition",
						options = border_colours,
						default_value = "Steel",
						tooltip = "border_colour_tooltip",
					},
					{
						setting_id = "expedition_border_colour_3",
						type = "dropdown",
						tab = "Expedition",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
					{
						setting_id = "expedition_colour",
						type = "group",
						tab = "Expedition",
						sub_widgets = {
							{ setting_id = "expedition_colour_R", type = "numeric", default_value = 192, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "expedition_colour_G", type = "numeric", default_value = 194, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "expedition_colour_B", type = "numeric", default_value = 110, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
					{
						setting_id = "expedition_pickups_colour",
						type = "group",
						tab = "Expedition",
						sub_widgets = {
							{ setting_id = "expedition_pickups_colour_R", type = "numeric", default_value = 223, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "expedition_pickups_colour_G", type = "numeric", default_value = 108, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "expedition_pickups_colour_B", type = "numeric", default_value = 110, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
					{
						setting_id = "expedition_currency_colour",
						type = "group",
						tab = "Expedition",
						sub_widgets = {
							{ setting_id = "expedition_currency_colour_R", type = "numeric", default_value = 233, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "expedition_currency_colour_G", type = "numeric", default_value = 185, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "expedition_currency_colour_B", type = "numeric", default_value = 110, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
					{
						setting_id = "expedition_reliquary_colour",
						type = "group",
						tab = "Expedition",
						sub_widgets = {
							{ setting_id = "expedition_reliquary_colour_R", type = "numeric", default_value = 108, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "expedition_reliquary_colour_G", type = "numeric", default_value = 158, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "expedition_reliquary_colour_B", type = "numeric", default_value = 255, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
					{
						setting_id = "expedition_remnants_colour",
						type = "group",
						tab = "Expedition",
						sub_widgets = {
							{ setting_id = "expedition_remnants_colour_R", type = "numeric", default_value = 137, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "expedition_remnants_colour_G", type = "numeric", default_value = 206, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "expedition_remnants_colour_B", type = "numeric", default_value = 125, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
					{
						setting_id = "expedition_crate_colour",
						type = "group",
						tab = "Expedition",
						sub_widgets = {
							{ setting_id = "expedition_crate_colour_R", type = "numeric", default_value = 198, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "expedition_crate_colour_G", type = "numeric", default_value = 110, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "expedition_crate_colour_B", type = "numeric", default_value = 0, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
				},
			},

			-- UNKNOWN
			{

				setting_id = "unknown_markers_settings",
				type = "group",
				tab = "Unknown",
				sub_widgets = {
					{
						setting_id = "unknown_enable",
						type = "checkbox",
						default_value = true,
						tab = "Unknown",
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "unknown_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tab = "Unknown",
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "unknown_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tab = "Unknown",
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "unknown_toggle_los",
						type = "keybind",
						function_name = "unknown_toggle_los",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						tab = "Unknown",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "unknown_max_distance",
						type = "numeric",
						tab = "Unknown",
						default_value = 50,
						range = { 0, 100 },
						step_size = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "unknown_scale",
						type = "numeric",
						tab = "Unknown",
						default_value = 100,
						range = { 50, 150 },
						step_size = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "unknown_alpha",
						type = "numeric",
						tab = "Unknown",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "unknown_colour",
						type = "group",
						tab = "Unknown",
						sub_widgets = {
							{ setting_id = "unknown_colour_R", type = "numeric", default_value = 255, range = { 0, 255 }, step_size = 1, tooltip = "colour_R_tooltip" },
							{ setting_id = "unknown_colour_G", type = "numeric", default_value = 255, range = { 0, 255 }, step_size = 1, tooltip = "colour_G_tooltip" },
							{ setting_id = "unknown_colour_B", type = "numeric", default_value = 255, range = { 0, 255 }, step_size = 1, tooltip = "colour_B_tooltip" },
						},
					},
					{
						setting_id = "unknown_border_colour",
						type = "dropdown",
						tab = "Unknown",
						options = border_colours,
						default_value = "Silver",
						tooltip = "border_colour_tooltip",
					},
				},
			},
		},
	},
}
